---
collections:
- ansible.posix
- devsec.hardening
- name: community.general
  version: 3.7.0

- name: git+https://github.com/leonardehrenfried/ansible-baseline.git
  type: git
  version: main



roles:
- src: geerlingguy.firewall
  version: 2.5.0
- src:  monolithprojects.github_actions_runner
  version: 1.12.3
