---
collections:
- ansible.posix
- devsec.hardening
- name: community.general
  version: 5.2.0
- name: leonardehrenfried.baseline
  version: 1.0.12

roles:
- src: geerlingguy.firewall
  version: 2.5.0
- src:  monolithprojects.github_actions_runner
  version: 1.16.0
