---
collections:
- name: ansible.posix
  version: 2.0.0
- name: devsec.hardening
  version: 10.2.0
- name: community.general
  version: 10.2.0
- name: leonardehrenfried.baseline
  version: 1.9.6

roles:
- src: geerlingguy.firewall
  version: 2.5.0
- src:  monolithprojects.github_actions_runner
  version: 1.16.0
