---
collections:
- ansible.posix
- devsec.hardening
- name: community.general
  version: 3.7.0
- name: leonardehrenfried.baseline
  version: 0.0.14

roles:
- src: geerlingguy.firewall
  version: 2.5.0
- src:  monolithprojects.github_actions_runner
  version: 1.12.3
