---

- name: Install base packages
  package:
    name:
      - htop
      - tree
      - neovim
      - cron-apt
      - autojump
      - jq
      - zsh
      - unzip
      - tar
      - git
    state: present

- name: Configure passwordless sudo
  ansible.builtin.copy:
    content: '%sudo ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/passwordless

- name: Create user and add to groups
  user:
    name: "{{ item.name }}"
    groups:
      - sudo
      - systemd-journal
    append: yes
    state: present
    createhome: yes
    shell: /bin/bash
  with_items: "{{ users }}"

- name: Set authorized keys taken from url
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.keys_url }}"
  with_items: "{{ users }}"
